### ISSUE TITLE
Doesn't work with Workbench 8

### ISSUE THREAD

**Issue by n8udd** [beckenrode/mysql-workbench-export-laravel-5-migrations#63]
I'm currently running Workbench 8.0.13, and on the *readme.md* file it says:

> Open a model in MySQL Workbench
> Tools > Catalog > Export Laravel 5 Migration

But this option is no longer under tools in the latest version of Workbench.

![image](https://user-images.githubusercontent.com/2293192/48139691-fea90500-e29e-11e8-9378-7d04ea1ee557.png)

**Comment by d8vjork** [comment]
I've not this problem, for me I can see the option but can't export

![image](https://user-images.githubusercontent.com/2331052/49575486-b252f280-f93a-11e8-971c-8687da3a746d.png)

**Comment by VeeeneX** [comment]
I've updated few things and tested it for latest MySQL Workbench, try it out :)

**Comment by jsdecena** [comment]
@VeeeneX How to export now? Bec the option for Tools > Catalog does not exists anymore

**Comment by VeeeneX** [comment]
@jsdecena Right under Tools > Catalog > Export Laravel 5 Migration, make sure you installed plugin and you are running MySQL Workbench 8+

**Comment by jsdecena** [comment]
@VeeeneX The user must go to the models first before the user can see it otherwise it is not available.
![Imgur](https://i.imgur.com/6EyEfxX.png)

**Comment by VeeeneX** [comment]
@jsdecena Yeap thats true :)

**Comment by Messhias** [comment]
Still problematic in the new version, now we can't choose the folder.

![screen shot 2019-01-31 at 12 09 48](https://user-images.githubusercontent.com/1161283/52040573-47482580-2551-11e9-9fc6-ba3a684bd8b1.png)

**Comment by zone1980** [comment]
+1, Cant select the target folder

**Comment by Messhias** [comment]
For now the solution I found out for that are 2:

1 - use SequelPro with laravel exportation plugin (but it's a quite old and doesn't support some things)
2 - copy all the migrations to a empty text file and create each migration for each table. 

Another problem I found out, the migrations are creating by the date of creation, what's problematic too because if we have some resolution tables and foreigns keys changes it'll broke our entire migration.

**Comment by d8vjork** [comment]
Now the submenu item disappear on version 8.0.15 :(

![image](https://user-images.githubusercontent.com/2331052/57360837-0e80a380-7173-11e9-9236-90f8df051080.png)

**Comment by Messhias** [comment]
> Now the submenu item disappear on version 8.0.15 :(
> 
> ![image](https://user-images.githubusercontent.com/2331052/57360837-0e80a380-7173-11e9-9236-90f8df051080.png)

It doesn't work in the new versions already.

**Comment by lbottoni** [comment]
same problem

**Comment by lbottoni** [comment]
resolved.
Before use tool->catalog we must import Data Models from Database-Reverse Engineer

**Comment by VeeeneX** [comment]
Does #65 fix it?

**Comment by Messhias** [comment]
No.

Em sáb, 22 de jun de 2019 18:37, VeeeneX <notifications@github.com>
escreveu:

**Comment by willhatchVista** [comment]
I'm running 8.0.16 on Win10, I just read through the manual for developing Workbench plugins and noticed  a difference in how they were declaring the plugin. It works for me the same as my other machine running Workbench 6.3 on Win10

**Comment by Messhias** [comment]
I'm running in the latest MacOS version and still not working.

*Best Regards,*

*Fabio William Conceição*

*Remote: https://remote.com/fabiowilliam <https://remote.com/fabiowilliam>*
*Tel/Whastapp: +971 52 503 3008*
*Skype: fabioo.william.conceicao*
*LinkedIn:
https://www.linkedin.com/in/fabio-william-concei%C3%A7%C3%A3o-379b9823/
<https://www.linkedin.com/in/fabio-william-concei%C3%A7%C3%A3o-379b9823/>*
*Github: **https://github.com/Messhias/ <https://github.com/Messhias/>*
*Upwork: https://www.upwork.com/o/profiles/users/_~0126d10487b9843f68/
<https://www.upwork.com/o/profiles/users/_~0126d10487b9843f68/>*


Em seg, 24 de jun de 2019 às 20:59, willhatchVista <notifications@github.com>
escreveu:
